var1 = [1, 2, 3, 4]

1. Print tipe dari var1

2. Print panjang dari var1

In [7]:
var1 = [1,2,3,4]
print("Tipe dari var1 adalah",type(var1))

print("elemen var1 : ",var1)

Tipe dari var1 adalah <class 'list'>
elemen var1 :  [1, 2, 3, 4]


In [8]:
print("banyaknya elemen adalah ",len(var1))

banyaknya elemen adalah  4


first = [11.25, 18.0, 20.0] 

second = [10.75, 9.50]

3. Gabungkan list first dengan second simpan dengan nama variabel full, print vraiabel full

4. Urutkan full dengan descending order simpan pada variabel full_sorted, print full_sorted

In [9]:
first = [11.25,18.0,20.0]
second = [10.75,9.50]
variabel_full = first+second
print("variabel_full adalah ", variabel_full)

variabel_full adalah  [11.25, 18.0, 20.0, 10.75, 9.5]


In [15]:
full_sorted = sorted(variabel_full,reverse=True)
print("Full_sorted adalah ", full_sorted)

Full_sorted adalah  [20.0, 18.0, 11.25, 10.75, 9.5]


area = [11.25, 18.0, 20.0, 10.75, 9.50]

5. Print hasilnya dengan menggunakan index() untuk mencari index dari 20.0 

6. Print  hasilnya dengan menggunakan count() berapa sering 14.5 muncul di area

7. Gunakan append dua kali untuk menambahkan 24.5 dan 15.45, print area

8. Balik urutan area dengan reverse(), print area


In [13]:
area = [11.25,18.0,20.0,10.75,9.50]
print(area[2])

20.0


In [14]:
print("Angka 14.5 muncul sebanyak",area.count(14.5))

Angka 14.5 muncul sebanyak 0


In [24]:
area.append(24.5)
area.append(15.45)
print("List area ",area)
del area[-2]
print("List area ",area)

List area  [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
List area  [11.25, 18.0, 20.0, 10.75, 9.5, 15.45]


In [25]:
del area[-3]
del area[-1]
print("List area ",area)

List area  [11.25, 18.0, 20.0, 9.5]


Masih ingat tentang lingkaran?
$$ Keliling = 2\pi r $$
$$ Luas = \pi r^2 $$

- Kamu bisa mendapatkan pi dengan cara import math kemudian panggil dengan math.pi


r = 0.43

9. Hitung keliling simpan dalam variabel keliling

10. Hitung luas simpan dalam variabel luas

11. Selesaikan Print ini : print("Keliling: " + ) dan print("Luas: " + )

In [17]:
import math
print ("Nilai pi : ",math.pi)
r=0.43

Keliling = 2*math.pi*r
print("Jadi keliling dari lingkaran adalah", Keliling)

Nilai pi :  3.141592653589793
Jadi keliling dari lingkaran adalah 2.701769682087222


In [19]:
Luas = math.pi*r*r
print("Jadi luas dari lingkaran adalah", Luas)

Jadi luas dari lingkaran adalah 0.5808804816487527


In [20]:
print("Keliling  : ",Keliling)
print("Luas      : ",Luas)

Keliling  :  2.701769682087222
Luas      :  0.5808804816487527


area_3 = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

12. Silahkan hapus 4 elemen terakhir, print area_3

In [21]:
area_3 = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, "bedroom", 10.75, "bathroom", 10.50, "poolhouse", 24.5, "garage", 15.45]
del area_3 [10:14]
print("List area_3 :", area_3,"dengan elemen sebanyak", len(area_3))

List area_3 : ['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5] dengan elemen sebanyak 10


area_4 = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

13. Ganti nilai dari "bathroom" menjadi 10.8, print area_4

14. Ganti "living room" menjadi "ruang tamu", print area_4

In [22]:
area_4 = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

area_4[-1]=10.8

print("List area_4 ",area_4)

List area_4  ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.8]


In [23]:
area_4[4]="ruang tamu"
    
print("List area_4 ",area_4)

List area_4  ['hallway', 11.25, 'kitchen', 18.0, 'ruang tamu', 20.0, 'bedroom', 10.75, 'bathroom', 10.8]
